package note

import (
	"net/http"

	"github.com/koopa0/yomihon/internal/origin"
	"github.com/koopa0/yomihon/internal/shell"
	"github.com/koopa0/yomihon/internal/ui/layouts"
	"github.com/koopa0/yomihon/internal/ui/pages"
	"github.com/koopa0/yomihon/internal/wording"
)

// LocalizedRouter changes only the mux's own method refusal. Registered
// handlers still enter through ServeHTTP, which fills their path wildcards and
// passes the original writer through, including its streaming capabilities.
func (h *Handler) LocalizedRouter(mux *http.ServeMux) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fallback, pattern := mux.Handler(r)
		if pattern == "" {
			reply := routerReply{header: make(http.Header)}
			fallback.ServeHTTP(&reply, r)
			if reply.code == http.StatusMethodNotAllowed {
				w.Header().Set("Allow", reply.header.Get("Allow"))
				h.refuseRequest(w, r, http.StatusMethodNotAllowed)
				return
			}
		}
		mux.ServeHTTP(w, r)
	})
}

// CrossOriginDenied answers the browser's refused cross-origin request before
// the router can enter any write face. The refusal keeps the reading shell so
// the reader can return through a safe navigation link.
func (h *Handler) CrossOriginDenied(w http.ResponseWriter, r *http.Request) {
	h.refuseRequest(w, r, http.StatusForbidden)
}

func (h *Handler) refuseRequest(w http.ResponseWriter, r *http.Request, code int) {
	lang := origin.Language(r)
	title, lede := wording.RequestMethodRefusedTitle.In(lang), wording.RequestMethodRefusedLede.In(lang)
	if code == http.StatusForbidden {
		title, lede = wording.RequestOriginRefusedTitle.In(lang), wording.RequestOriginRefusedLede.In(lang)
	}
	authority := h.sources.Status()
	snap := h.sources.Snapshot().Capture()
	view := pages.RequestRefusedView{Title: title, Lede: lede, Sidebar: pages.NewSidebar(shell.Project(h.sources.VaultName, authority, snap), "")}
	w.Header().Set("Content-Type", "text/html; charset=utf-8")
	w.WriteHeader(code)
	if err := pages.RequestRefused(view, layouts.ChromeFromRequest(r, title)).Render(r.Context(), w); err != nil && r.Context().Err() == nil {
		h.sources.Log.Error("render request refusal", "error", err)
	}
}

// routerReply observes only handlers generated by ServeMux itself, never a
// registered handler. Its body is discarded because the mux's English 405 is
// replaced, while redirects and other responses are sent normally afterward.
type routerReply struct {
	header http.Header
	code   int
}

func (r *routerReply) Header() http.Header { return r.header }
func (r *routerReply) WriteHeader(code int) {
	if r.code == 0 {
		r.code = code
	}
}
func (r *routerReply) Write(p []byte) (int, error) {
	if r.code == 0 {
		r.code = http.StatusOK
	}
	return len(p), nil
}
