package judge_test

// Each fault enters the existing compiler-overlay driver and reads the actual
// page and complete public check output, with its unchanged prose controls.
func stage5Mutations() []agreementMutation {
	return []agreementMutation{
		{Name: "stage5-linkified-code", Property: "S5", Identity: "linkified-code", File: "internal/render/section.go", Function: "addPresentationAutolinks", Needle: "for link := range autolinks {", Fault: "for link := range autolinks { if true { continue }", Package: "./internal/judge", ControlTest: "TestAgreementLinkifiedCode"},
		{Name: "stage5-autolink-observation", Property: "S5", Identity: "linkified-code", File: "internal/graph/body.go", Function: "collectSourceNode", Needle: "o.autolinks = append(o.autolinks, Span{Start: start, Stop: start + len(label)})", Fault: "o.autolinks = append(o.autolinks, Span{Start: start, Stop: start})", Package: "./internal/judge", ControlTest: "TestAgreementAutolinkObservation"},
		{Name: "stage5-autolink-projection", Property: "S5", Identity: "linkified-code", File: "internal/graph/bodyprojection.go", Function: "projectProse", Needle: "f.autolinks = append(f.autolinks, span)", Fault: "f.autolinks = append(f.autolinks, Span{Start: span.Start, Stop: span.Start})", Package: "./internal/judge", ControlTest: "TestAgreementAutolinkProjection"},
		{Name: "stage5-autolink-accessor", Property: "S5", Identity: "linkified-code", File: "internal/graph/body.go", Function: "Autolinks", Needle: "return bodyValues(f.data.autolinks)", Fault: "return bodyValues(f.data.autolinks[:0])", Package: "./internal/judge", ControlTest: "TestAgreementAutolinkAccessor"},
		{Name: "stage5-autolink-check", Property: "S5", Identity: "linkified-code", File: "internal/judge/extract.go", Function: "structureFrom", Needle: "for link := range facts.Autolinks() {", Fault: "for link := range facts.Autolinks() { if true { continue }", Package: "./internal/judge", ControlTest: "TestAgreementAutolinkCheck"},
		{Name: "stage5-autolink-sequence", Property: "S5", Identity: "linkified-code", File: "internal/sequence/sequence.go", Function: "skipFacts", Needle: "for link := range facts.Autolinks() {", Fault: "for link := range facts.Autolinks() { if true { continue }", Package: "./internal/judge", ControlTest: "TestAgreementAutolinkSequence"},
		{Name: "stage5-unused-continuation", Property: "S5", Identity: "unused-continuation", File: "internal/graph/body.go", Function: "observeBodyRequested", Needle: "for _, span := range bodyStrayBlocks(node) {", Fault: "for _, span := range []Span(nil) {", Package: "./internal/judge", ControlTest: "TestAgreementUnusedFootnoteContinuation"},
		{Name: "stage5-title-comment-page", Property: "S5", Identity: "title-comment-page", File: "internal/render/render.go", Function: "htmlReadingIn", Needle: "removeBodyFirstH1(title, stripped.text, stripped.roleGaps...)", Fault: "removeBodyFirstH1(title, stripped.text)", Package: "./internal/render", ControlTest: "TestTitleHeadingSkipsInvisibleCommentRoles"},
		{Name: "stage5-title-comment-role", Property: "S5", Identity: "title-comment-role", File: "internal/render/render.go", Function: "removeBodyFirstH1", Needle: "for _, gap := range gaps {", Fault: "for _, gap := range []string(nil) {", Package: "./internal/lexical", ControlTest: "TestDroppedTitleKeepsMainLanding"},
		{Name: "stage5-code-boundary", Property: "S5", Identity: "code-boundary", File: "internal/render/wikilink.go", Function: "replaceOutside", Needle: "withinAny(skip, loc[0], loc[0]+1)", Fault: "withinAny(skip, loc[0], loc[1])", Package: "./internal/judge", ControlTest: "TestAgreementStage5CodeBoundary"},
		{Name: "stage5-list-fence", Property: "S5", Identity: "list-fence", File: "internal/render/section.go", Function: "presentationCodeLines", Needle: "for code := range codes {", Fault: "for code := range codes { if code.Kind == graph.CodeFence { continue }", Package: "./internal/judge", ControlTest: "TestAgreementStage5ListFence"},
		{Name: "stage5-list-fence-rail", Property: "S5", Identity: "list-fence", File: "internal/render/section.go", Function: "presentationCodeLines", Needle: "reading.fenceContent = true", Fault: "reading.fenceContent = false", Package: "./internal/judge", ControlTest: "TestAgreementStage5ListFenceRail"},
		{Name: "stage5-wrapped-code", Property: "S5", Identity: "wrapped-code", File: "internal/render/section.go", Function: "presentationCodeLines", Needle: "reading.spans = append(reading.spans, [2]int{max(0, code.Span.Start-at), min(len(line), code.Span.Stop-at)})", Fault: "if code.Kind != graph.CodeInline { reading.spans = append(reading.spans, [2]int{max(0, code.Span.Start-at), min(len(line), code.Span.Stop-at)}) }", Package: "./internal/judge", ControlTest: "TestAgreementStage5WrappedCode"},
		{Name: "stage5-fence-info", Property: "S5", Identity: "fence-info", File: "internal/graph/bodygrammar.go", Function: "Open", Needle: "fact := CodeFact{Kind: CodeFence, Span: Span{Start: start, Stop: segment.Stop}", Fault: "fact := CodeFact{Kind: CodeFence, Span: Span{Start: segment.Stop, Stop: segment.Stop}", Package: "./internal/judge", ControlTest: "TestAgreementStage5FenceInfo"},
		{Name: "stage5-percent-code", Property: "S5", Identity: "percent-code", File: "internal/graph/bodycomments.go", Function: "stripBodyCommentMark", Needle: "In(state.code, open) || In(state.extraCode, open)", Fault: "In(state.extraCode, open)", Package: "./internal/judge", ControlTest: "TestAgreementStage5PercentCode"},
		{Name: "stage5-html-code", Property: "S5", Identity: "html-code", File: "internal/graph/bodycomments.go", Function: "stripBodyCommentLine", Needle: "case mark >= 0:", Fault: "case mark >= 0 && (strings.IndexByte(line, '`') < 0 || mark < strings.IndexByte(line, '`')):", Package: "./internal/judge", ControlTest: "TestAgreementStage5HtmlCode"},
		{Name: "stage5-indent-page", Property: "S5", Identity: "indent-page", File: "internal/render/wikilink.go", Function: "scanOrdinaryLine", Needle: "if !st.owned[st.i] && !st.code[st.i].block {", Fault: "if !st.owned[st.i] {", Package: "./internal/judge", ControlTest: "TestAgreementStage5IndentPage"},
		{Name: "stage5-indent-excerpt", Property: "S5", Identity: "indent-excerpt", File: "internal/render/blockanchor.go", Function: "UnanchorableLines", Needle: "code[i].block || UnanchorableLine(line)", Fault: "(false && code[i].block) || UnanchorableLine(line)", Package: "./internal/judge", ControlTest: "TestAgreementStage5IndentExcerpt"},
		{Name: "stage5-indent-judge", Property: "S5", Identity: "indent-judge", File: "internal/render/blockanchor.go", Function: "UnanchorableLines", Needle: "code[i].block || UnanchorableLine(line)", Fault: "(false && code[i].block) || UnanchorableLine(line)", Package: "./internal/judge", ControlTest: "TestAgreementStage5IndentJudge"},
		{Name: "stage5-unused-definition", Property: "S5", Identity: "unused-definition", File: "internal/render/wikilink.go", Function: "keepEffects", Needle: "if !m.emittedInline[index] {", Fault: "if false && !m.emittedInline[index] {", Package: "./internal/judge", ControlTest: "TestAgreementStage5UnusedDefinition"},
		{Name: "stage5-title-footnote", Property: "S5", Identity: "title-footnote", File: "internal/graph/bodygrammar.go", Function: "parseBodyFootnote", Needle: "if calloutTitleAt(reader.Source(), position.Start) {", Fault: "if false && calloutTitleAt(reader.Source(), position.Start) {", Package: "./internal/judge", ControlTest: "TestAgreementStage5TitleFootnote"},
		{Name: "stage5-marker-raw", Property: "S5", Identity: "marker-authority", File: "internal/render/render.go", Function: "renderBody", Needle: "strings.ContainsRune(inlinePlaceholderRunes, r)", Fault: "false && strings.ContainsRune(inlinePlaceholderRunes, r)", Package: "./internal/judge", ControlTest: "TestAgreementStage5MarkerRaw"},
		{Name: "stage5-marker-numeric", Property: "S5", Identity: "marker-authority", File: "internal/render/authoredtext.go", Function: "renderAuthoredText", Needle: "if value[start] == '&' && strings.ContainsAny(string(decoded), inlinePlaceholderRunes) {", Fault: "if false && value[start] == '&' && strings.ContainsAny(string(decoded), inlinePlaceholderRunes) {", Package: "./internal/judge", ControlTest: "TestAgreementStage5MarkerNumeric"},
		{Name: "stage5-marker-block", Property: "S5", Identity: "marker-authority", File: "internal/graph/bodycomments.go", Function: "neutralizeBodyBlockMarker", Needle: "if strings.HasPrefix(body.text[open:], RenderedBlockMarkerOpen) && closed && span.Stop <= lineStop {", Fault: "if false && strings.HasPrefix(body.text[open:], RenderedBlockMarkerOpen) && closed && span.Stop <= lineStop {", Package: "./internal/judge", ControlTest: "TestAgreementStage5MarkerBlock"},
		{Name: "stage5-percent-role", Property: "S5", Identity: "percent-role", File: "internal/graph/bodycomments.go", Function: "stripBodyCommentMark", Needle: "if strings.TrimSpace(prefix) == \"\" {", Fault: "if false && strings.TrimSpace(prefix) == \"\" {", Package: "./internal/judge", ControlTest: "TestAgreementStage5PercentRole"},
		{Name: "stage5-percent-geometry", Property: "S5", Identity: "percent-role", File: "internal/graph/bodycomments.go", Function: "stripBodyProjection", Needle: "graphBlank && !state.htmlLine && strings.TrimSpace(line[len(authoredPrefix):]) != \"\"", Fault: "false && graphBlank && !state.htmlLine && strings.TrimSpace(line[len(authoredPrefix):]) != \"\"", Package: "./internal/judge", ControlTest: "TestAgreementStage5PercentGeometry"},
		{Name: "stage5-html-role", Property: "S5", Identity: "html-role", File: "internal/graph/bodycomments.go", Function: "stripBodyHTMLComment", Needle: "block && closed && span.Stop <= lineStop", Fault: "false && block && closed && span.Stop <= lineStop", Package: "./internal/judge", ControlTest: "TestAgreementStage5HtmlRole"},
		{Name: "stage5-coordinates", Property: "S5", Identity: "coordinates", File: "internal/judge/extract.go", Function: "extractWikilinksFrom", Needle: "bodyStartLine + strings.Count(body[:raw.offset], \"\\n\")", Fault: "bodyStartLine", Package: "./internal/judge", ControlTest: "TestAgreementStage5Coordinates"},
		{Name: "stage5-projection-source", Property: "S5", Identity: "projection-source", File: "internal/render/comment.go", Function: "sourceSlice", Needle: "for _, gap := range s.roleGaps {", Fault: "for _, gap := range []string(nil) {", Package: "./internal/judge", ControlTest: "TestAgreementStage5ProjectionSource"},
		{Name: "stage5-role-gap-accessor", Property: "S5", Identity: "projection-source", File: "internal/graph/body.go", Function: "PresentationRoleGaps", Needle: "bodyValues(f.data.roleGaps)", Fault: "bodyValues(f.data.roleGaps[:0])", Package: "./internal/judge", ControlTest: "TestAgreementStage5RoleGapAccessor"},
		{Name: "stage5-presentation-accessor", Property: "S5", Identity: "percent-role", File: "internal/graph/body.go", Function: "PresentationSource", Needle: "return f.data.presentation", Fault: "return f.data.commentFree", Package: "./internal/judge", ControlTest: "TestAgreementStage5PresentationAccessor"},
		{Name: "stage5-preview-role", Property: "S5", Identity: "preview-role", File: "internal/render/render.go", Function: "HTMLExcerptIn", Needle: "excerpt.Source(), excerpt.body,", Fault: "excerpt.Source(), strippedBody{text: excerpt.Source(), address: excerpt.body.address},", Package: "./internal/note", ControlTest: "TestPreviewRetainsCommentBlockRoles"},
		{Name: "stage5-preview-budget", Property: "S5", Identity: "preview-budget", File: "internal/render/section.go", Function: "Cap", Needle: "source := e.Source()", Fault: "source := e.body.text", Package: "./internal/render", ControlTest: "TestExcerptBudgetCountsAuthoredBytes"},
	}
}
